# Generated by Django 2.1.13 on 2019-10-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Asset Class',
                'verbose_name_plural': 'Asset Classes',
                'ordering': ['asset_class_name'],
            },
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Benchmark',
                'verbose_name_plural': 'Benchmarks',
                'ordering': ['benchmark_name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentCounselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Investment Counselor',
                'verbose_name_plural': 'Investment Counselors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentGuideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(max_length=150, verbose_name='Portfolio Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
                ('investment_counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InvestmentCounselor')),
            ],
            options={
                'verbose_name': 'Investment Guideline',
                'verbose_name_plural': 'Investment Guidelines',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Strategist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Strategist',
                'verbose_name_plural': 'Strategists',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=150, verbose_name='Strategy Name')),
                ('is_enhanced', models.BooleanField(default=False)),
                ('is_impact', models.BooleanField(default=False)),
                ('asset_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AssetClass')),
                ('benchmark_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Benchmark')),
                ('product_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('strategist_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Strategist')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['strategy_name'],
            },
        ),
        migrations.AddField(
            model_name='investmentguideline',
            name='strategies',
            field=models.ManyToManyField(db_constraint=False, to='core.Strategy'),
        ),
    ]
