# Generated by Django 2.1.13 on 2019-11-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191010_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentguideline',
            name='strategies',
            field=models.ManyToManyField(related_name='investmentguideline', through='core.InvestmentGuidelineOptions', to='core.Strategy'),
        ),
    ]
