# Generated by Django 2.1.13 on 2019-10-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentguidelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='is_enhanced',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='is_impact',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='asset_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.AssetClass', verbose_name='Asset Class'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='benchmark_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.Benchmark', verbose_name='Benchmark'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategist_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.Strategist', verbose_name='Strategist'),
        ),
    ]
