# Generated by Django 2.1.13 on 2019-10-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentguidelines', '0002_auto_20191007_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGuideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(max_length=150, verbose_name='Portfolio Code')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
                ('investment_counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                           to='investmentguidelines.InvestmentCounselor')),
            ],
            options={
                'verbose_name': 'Investment Guideline',
                'verbose_name_plural': 'Investment Guidelines',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentGuidelineOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enhanced', models.BooleanField(default=False)),
                ('is_impact', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='investmentguidelineoptions',
            name='investment_guideline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.InvestmentGuideline'),
        ),
        migrations.AddField(
            model_name='investmentguidelineoptions',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.Strategy'),
        ),
        migrations.AddField(
            model_name='investmentguideline',
            name='strategies',
            field=models.ManyToManyField(through='investmentguidelines.InvestmentGuidelineOptions',
                                         to='investmentguidelines.Strategy'),
        ),

    ]
