# Generated by Django 2.1.13 on 2019-10-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentguidelines', '0003_auto_20191008_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentguidelineoptions',
            name='investment_guideline',
        ),
        migrations.RemoveField(
            model_name='investmentguidelineoptions',
            name='strategy',
        ),
        migrations.AddField(
            model_name='investmentguidelineoptions',
            name='investmentguideline_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.InvestmentGuideline'),
        ),
        migrations.AddField(
            model_name='investmentguidelineoptions',
            name='strategy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investmentguidelines.Strategy'),
        ),
    ]
