# Generated by Django 2.1.13 on 2019-10-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentguidelines', '0005_auto_20191008_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentguidelineoptions',
            options={'ordering': ['investmentguideline', 'strategy'], 'verbose_name': 'Investment Guideline Option', 'verbose_name_plural': 'Investment Guideline Options'},
        ),
        migrations.AlterField(
            model_name='investmentguideline',
            name='strategies',
            field=models.ManyToManyField(related_name='investmentguidelines', through='investmentguidelines.InvestmentGuidelineOptions', to='investmentguidelines.Strategy'),
        ),
    ]
